# Aula 1- Introdução ao Python

## Sobre o Python
* Linguagem de programação de alto nível, propósito geral, interpretada, imperativa, orientada a objetos, funcional, com tipagem forte e dinâmica;
* Criada por Guido van Rossum em 1991;
* Modelo de desenvolvimento open-source;
* Gerenciada pela organização sem fins lucrativos Python Software Foundation;
* Altamente utilizada para scripts, machine learning, processamento de imagens, web, computação científica, dentre outros;
* Usada na Wikipedia, Google, Yahoo!, NASA, Facebook, Amazon, Instagram, Spotify, Reddit etc.

A filosofia do Python é enfatizar a importância do esforço do programador sobre o esforço computacional, dando ênfase à legibilidade do código sobre a velocidade.

Foi criada com base na linguagem ABC, possuindo sintaxe influencidada pelo C, além de compreensão de listas, funções anônimas e função map inspiradas do Haskell. Os iteradores são baseados na Icon, tratamento de exceção e módulos da Modula-3 e expressões regulares de Perl.

## Declarando variáveis

Para declarar variáveis no Python, basta utilizar a sintaxe
```python
nome = valor```

Alguns exemplos:

In [3]:
# inteiros:
idade = 21

# pontos flutuantes:
altura = 1.65

# strings:
nome = "maria antonieta"

# booleanos:
gosta_de_python = True

## Funções úteis

Dentre algumas funções, podemos destacar:
```python
input("mensagem opcional de entrada") # lê do stdin
print(valor) # escreve no stdout
int(minha_string) # transforma a string em inteiro
float(minha_string) # transforma a string em ponto flutuante```

In [4]:
# Printando valores:
print(idade)
print(altura)
print(nome)
print(gosta_de_python)

# Lendo valores:
meu_nome = input("Entre com seu nome:")

# '+' concatena duas strings:
print("Olá " + meu_nome)

# Podemos usar 'aspas simples' ou "aspas duplas" para strings:
minha_idade = int(input('Entre com sua idade:'))

# Também podemos usar o próprio print para concatenar:
print('Sua idade é', minha_idade)

21
1.65
maria antonieta
True
Entre com seu nome:Douglas
Olá Douglas
Entre com sua idade:21
Sua idade é 21


Caso um cast não seja válido, o Python lançará um `ValueException`:
![ValueException](int_exception.png)

## Operadores aritméticos:

O Python oferece vários operadores que estamos familiarizados, tais como:
```python
soma = x + y
subtracao = x - y
multiplicacao = x * y
divisao = x / y
divisao_truncada = x // y # arredonda para baixo
exponenciacao = x ** y # x elevado a y
resto_divisao = x % y```

In [5]:
x = float(input("Entre com x: "))
y = float(input("Entre com y: "))

soma = x + y
subtracao = x - y
multiplicacao = x * y
divisao = x / y
divisao_truncada = x // y 
exponenciacao = x ** y
resto_divisao = x % y

print()

print("Soma:", soma)
print("Subtração:", subtracao)
print("Multiplicação:", multiplicacao)
print("Divisão:", divisao)
print("Divisão Truncada:", divisao_truncada)
print("Exponenciação:", exponenciacao)
print("Resto da Divisão:", resto_divisao)

Entre com x: 2
Entre com y: 3

Soma: 5.0
Subtração: -1.0
Multiplicação: 6.0
Divisão: 0.6666666666666666
Divisão Truncada: 0.0
Exponenciação: 8.0
Resto da Divisão: 2.0


## Estruturas de decisão e operadores de comparação e lógicos

![Um pouco de humor](if_else.gif)

Estruturas de decisão são recursos da linguagem que permitem ao programador fazer determinadas ações de acordo com um predicado. Elas têm a seguinte sintaxe:
```python
if condicao1:
    comandos
elif condicao2:
    comandos
elif condicao3:
    comandos
else:
    comandos```
    
As condições devem ser coercíveis para `bool` para poderem ser executadas.

**Atenção! No Python, é necessário que os blocos estejam propriamente indentados, ou o interpretador irá lançar um erro.**

In [6]:
if True:
    print("Verdadeiro")
else:
    print("Absurdo")

Verdadeiro


### Operadores de comparação

Os operadores de comparação permitem verificar igualdades e desigualdades entre valores, sendo possível verificar se tal condição é verdadeira ou falsa. Dentre eles temos:
```python
igual = x == y
diferente = x != y
menor = x < y
maior = x > y
menor_igual = x <= y
maior_igual = x >= y```

### Operadores lógicos

Os operadores lógicos são operadores que recebem `bools` como argumento e retornam um `bool`. Dentre eles podem destacar:
```python
e_logico = x and y
ou_logico = x or y
nao_logico = not x```

Abaixo temos um exemplo onde verificamos 

In [7]:
x = float(input("Entre com um valor: "))
y = float(input("Entre com outro valor: "))

if x > y:
    print(x, ">", y)
elif x == y and x == 42:
    print("A resposta para a vida, o universo e tudo mais")
elif x < 0 or y < 0:
    print("Algum valor é negativo")
else:
    print("Nenhum bloco acima foi executado")

Entre com um valor: 1
Entre com outro valor: 0
1.0 > 0.0


Outra coisa interessante é a capacidade do Python de aninhar operadores de comparação:

In [6]:
x = float(input("Entre com um valor:"))

if 0 < x <= 10:
    print(x, "é maior que 0 e menor ou igual a 10")
elif -100 <= x <= 0:
    print(x, "está entre -100 e 0")
else:
    print(x, "é maior que 10 ou menor que -100")

Entre com um valor:-5
-5.0 está entre -100 e 0


## Listas

No Python, podemos criar listas heterogêneas (isto é, listas podem conter qualquer tipo de variável). Por exemplo:

In [7]:
lista1 = ["Multimídia", 100, True]
print(lista1)

['Multimídia', 100, True]


### Métodos e funções úteis para listas

Para manipular listas, podemos destacar algumas funções e métodos úteis:

In [8]:
lista2 = [42, "Python", 3.14159, lista1]

# Tamanho de uma lista:
print("Tamanho da lista:", len(lista2))

# Adicionar um novo elemento:
lista2.append(1.88)
print("Lista com o novo elemento adicionado:", lista2)

# Acessando valores individuais:
print("Elemento na posição 0:", lista2[0]) # Pega o elemento na posição 0.
print("Último elemento:", lista2[-1]) # Pega o último elemento.
print("Penúltimo elemento:", lista2[-2]) # Pega o penúltimo elemento.
print("Elemento na posição 2 e 3:", lista2[2:4]) # Pega os elementos 2 e 3. Obs.: Primeiro valor incluso e último excluso.

# Reverter lista:
lista2.reverse()
print("Lista invertida:", lista2)

# Ordenação (para listas homogêneas):
lista3 = [8, 4, 3, 10, -20]

lista3.sort()
print("Lista ordenada crescente:", lista3)

lista3.sort(reverse=True)
print("Lista ordenada decrescente:", lista3)

Tamanho da lista: 4
Lista com o novo elemento adicionado: [42, 'Python', 3.14159, ['Multimídia', 100, True], 1.88]
Elemento na posição 0: 42
Último elemento: 1.88
Penúltimo elemento: ['Multimídia', 100, True]
Elemento na posição 2 e 3: [3.14159, ['Multimídia', 100, True]]
Lista invertida: [1.88, ['Multimídia', 100, True], 3.14159, 'Python', 42]
Lista ordenada crescente: [-20, 3, 4, 8, 10]
Lista ordenada decrescente: [10, 8, 4, 3, -20]


## Estruturas de repetição

No Python, temos acesso a duas estruturas de repetição: `while` e `for`.

### while

Executa comandos dentro do bloco `while` enquanto a condição é verdadeira:

In [9]:
x = 512

while x > 0:
    print("x =", x)
    x //= 2 # o mesmo que x = x // 2

x = 512
x = 256
x = 128
x = 64
x = 32
x = 16
x = 8
x = 4
x = 2
x = 1


### for

Adicionamente, temos o `for`, que permite iterar por valores dentro de uma estrutura:

In [10]:
lista2 = [42, "Python", 3.14159]

for valor in lista2:
    print(valor)

42
Python
3.14159


In [11]:
print("[0, 5):")
for i in range(5):
    print(i)

print()
    
print("[2, 8):")
for j in range(2, 8):
    print(j)
    
print()
    
print("[4, 9) com passo 2:")
for k in range(4, 9, 2):
    print(k)

[0, 5):
0
1
2
3
4

[2, 8):
2
3
4
5
6
7

[4, 9) com passo 2:
4
6
8


## Tuplas

Tuplas funcionam como listas heterogêneas de tamanho fixo e imutáveis.

In [12]:
louis = ("Louis XIV", "França")
beethoven = ("Beethoven", "Alemanha")
aristoteles = ("Aristóteles", "Grécia")

# Acessando valores:
print(louis[0])

# Desconstrução de tuplas:
(nome1, pais1) = aristoteles
print(nome1, pais1)

Louis XIV
Aristóteles Grécia


## Funções

Funções fornecem uma forma de reutilizar código e deixar ele mais organizado. A sintaxe é como abaixo:
```python
def nome_funcao(argumento1, argumento2, argumento3=opcional1, argumento4=opcional2):
    corpo_funcao
    return valor # obs.: return não é obrigatório```

Abaixo temos exemplos de funções:

In [13]:
# Função com retorno:
def soma(x, y=5):
    z = x + y
    return z

print(soma(1, 3))
print(soma(3))

4
8


In [14]:
# Função sem retorno:
def mostra_paridade(valores):
    for valor in valores:
        if valor % 2 == 0:
            print(valor, "é par")
        else:
            print(valor, "é ímpar")
            
mostra_paridade(range(0, 10))

0 é par
1 é ímpar
2 é par
3 é ímpar
4 é par
5 é ímpar
6 é par
7 é ímpar
8 é par
9 é ímpar


## Funções anônimas

Funções anônimas (também chamadas de `lambdas`) são funções que podem ser salvas em variáveis. Exemplo:

In [15]:
mostra_pessoa = lambda nome, idade: nome + " tem " + str(idade) + " anos."

print(mostra_pessoa("Napoleão", 250))

Napoleão tem 250 anos.


In [16]:
pontos = [(2, 5), (-1, 0), (6, 3), (2, -3)]
pontos_ordenados_em_x = sorted(pontos, key=lambda p: p[0])

print(pontos_ordenados_em_x)

[(-1, 0), (2, 5), (2, -3), (6, 3)]


## Arrays do NumPy
Embora as listas do Python sejam úteis para o desenvolvimento no dia-a-dia, daremos preferência aos arrays do NumPy, por serem mais eficientes e oferecerem mais operações úteis relacionadas à manipulação de vetores e matrizes algébricas.

O primeiro passo é importar o NumPy:

In [17]:
import numpy as np
# obs.: também poderíamos importar tudo do módulo:
# from numpy import *

### Vetores

In [18]:
# Criação de vetores:
vetor = np.array([2, 3, 5, 7, 11])

# Shape mostra as dimensões do array:
print("Vetor:", vetor, "\nDimensão:", vetor.shape)

Vetor: [ 2  3  5  7 11] 
Dimensão: (5,)


In [19]:
# Também podemos especificar o tipo das variáveis dentro do array:
vetor_float = np.array([1, 0.1, 0.01, 0.001])
print("Vetor:", vetor_float, "   Dimensão:", vetor_float.shape, "   Tipo:", vetor_float.dtype)

print()

vetor_int = np.array([1, 1, 2, 3, 5, 8], np.uint8)
print("Vetor:", vetor_int, "               Dimensão:", vetor_int.shape, "   Tipo:", vetor_int.dtype)

# Para mais informações: https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

Vetor: [1.    0.1   0.01  0.001]    Dimensão: (4,)    Tipo: float64

Vetor: [1 1 2 3 5 8]                Dimensão: (6,)    Tipo: uint8


### Matrizes

In [20]:
# Criação de matrizes:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matriz:\n", matriz, "\n\nDimensão:", matriz.shape)

Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Dimensão: (3, 3)


### Funções e operações relevantes

#### Criação de arrays:

In [21]:
print('Array tamanho 2x4 preenchido com 1:')
print(np.ones((2, 4)))

print('\nArray tamanho 2x4x3 preenchido com 0:')
print(np.zeros((3, 2, 4))) # Ordem invertida: [página, linha, coluna].

print('\nArray 3x4 com valores aleatórios em [0, 10):')
np.random.seed(42) # Opcional.
print(np.random.randint(10, size=(3, 4)))

print('\nArray com valores em [0, 1) e passo 0.1:')
print(np.arange(0, 1, 0.1))

Array tamanho 2x4 preenchido com 1:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array tamanho 2x4x3 preenchido com 0:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

Array 3x4 com valores aleatórios em [0, 10):
[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]]

Array com valores em [0, 1) e passo 0.1:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### Transposta e concatenação:

In [22]:
matriz_2x3 = np.array([[0, 1, 2], [3, 4, 5]])
print('Matriz 2x3:')
print(matriz_2x3)

print('\nTransposta:')
print(matriz_2x3.T)

matriz_2x2 = np.array([[6, 7], [8, 9]])
print('\nMatriz 2x2:')
print(matriz_2x2)

matriz_3x3 = np.array([[6, 7, 8], [9, 10, 11], [12, 13, 14]])
print('\nMatriz 3x3:')
print(matriz_3x3)

print('\nMatriz 2x3 e Matriz 3x3 - Concatenação no eixo das linhas (eixo 0):')
print(np.concatenate([matriz_2x3, matriz_3x3], axis=0))

print('\nMatriz 2x3 e Matriz 2x2 - Concatenação no eixo das colunas (eixo 1):')
print(np.concatenate([matriz_2x3, matriz_2x2], axis=1))

Matriz 2x3:
[[0 1 2]
 [3 4 5]]

Transposta:
[[0 3]
 [1 4]
 [2 5]]

Matriz 2x2:
[[6 7]
 [8 9]]

Matriz 3x3:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Matriz 2x3 e Matriz 3x3 - Concatenação no eixo das linhas (eixo 0):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Matriz 2x3 e Matriz 2x2 - Concatenação no eixo das colunas (eixo 1):
[[0 1 2 6 7]
 [3 4 5 8 9]]


#### Indexação:

A indexação funciona da mesma forma que listas normais do Python:

In [23]:
# Elementos individuais:
matriz_3x4 = np.array([[0,  1,  2],
                       [3,  4,  5],
                       [6,  7,  8],
                       [9, 10, 11]])

print("Linha de índice 0:", matriz_3x4[0]) # linha de índice 0
print("Linha 2 e coluna 1:", matriz_3x4[2, 1]) # linha de índice 2 ([6, 7, 8]) e coluna de índice 1
print("Todas linhas e coluna 1:", matriz_3x4[:, 1]) # todas as linhas e coluna de índice 1
print("Linhas [1, 3) e colunas >= 1:\n", matriz_3x4[1:3, 1:]) # linhas [1, 3), todas as colunas a partir de 1

Linha de índice 0: [0 1 2]
Linha 2 e coluna 1: 7
Todas linhas e coluna 1: [ 1  4  7 10]
Linhas [1, 3) e colunas >= 1:
 [[4 5]
 [7 8]]


#### Operações:

In [24]:
print('Multiplicação com escalar:')
print(np.ones((2, 3)) * 2)

print('\nSoma com escalar:')
print(np.zeros(6) + 3)

print('\nSoma ponto-a-ponto:')
# Equivalente a [[1, 1], [1, 1]] + [[10, 10], [10, 10]]:
print(np.ones((2, 2)) + 10 * np.ones((2, 2)))

print('\nMultiplicação ponto-a-ponto:')
# Equivalente a [2, 2, 2, 2] * [5, 5, 5, 5]:
print((2 * np.ones(4)) * (5 * np.ones(4)))

print('\nMultiplicação matricial:')
print(
    np.matmul(
        np.array([[1, 2],
                  [3, 4]]),
        np.array([[5, 6],
                  [7, 8]])))

print('\nProduto escalar:')
#Equivalente a 1 * (-1) + 2 * 0 + 3 * 1:
print(np.dot(np.array([1, 2, 3]), np.array([-1, 0, 1])))

Multiplicação com escalar:
[[2. 2. 2.]
 [2. 2. 2.]]

Soma com escalar:
[3. 3. 3. 3. 3. 3.]

Soma ponto-a-ponto:
[[11. 11.]
 [11. 11.]]

Multiplicação ponto-a-ponto:
[10. 10. 10. 10.]

Multiplicação matricial:
[[19 22]
 [43 50]]

Produto escalar:
2


# Exercícios

1. Crie dois arrays 8x8x3, com valores aleatórios do tipo np.uint8 no intervalo de 0 a 10 (inclusive). Chame as variáveis de `a` e `b`.

In [5]:
from numpy import random as rd
import numpy as np
# Dica 1: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html
# Dica 2: Ordem: página x linha x coluna.
vetor_int = np.array([rd.randint(10, size=(8)),
                      rd.randint(10, size=(8)),
                      rd.randint(10, size=(3))])
print(vetor_int)

[array([7, 1, 1, 4, 1, 9, 5, 7]) array([7, 3, 6, 6, 3, 7, 6, 4])
 array([6, 9, 7])]


2. Crie uma nova matriz `c`, cujos valores são as médias aritméticas dos valores (ponto-a-ponto) das matrizes criadas no exercício 1.

3. Concatene as matrizes `a`, `b` e `c` horizontalmente, e depois guarde a subarray composta pelas linhas 1 a 7 (inclusive), colunas 0 a 3 (inclusive) e página 1.

In [ ]:
# Dica: Ordem de acesso: [página (eixo 0), linha (eixo 1), coluna (eixo 2)].

4. Multiplique a página 0 da matriz `a` com a página 1 da matriz `b` (faça multiplicação matricial).

5. Crie uma função que receba um array bidimensional e retorne uma tupla `(m, p)`, onde `m` é o maior valor e `p` é a posição `(x, y)` no array onde se encontra `m`. Faça uso do `while` ou do `for` vistos acima. Caso tenha mais de uma posição com valor máximo, utilize a posição mais antiga.

In [ ]:
# Dica: Infinito no numpy = np.inf

6. Pesquise sobre as funções `max`, `unravel_index` e `argmax` do NumPy e refaça o exercício 5 sem utilizar estrutura de repetição.

In [ ]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html?highlight=argmax#numpy.argmax
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.unravel_index.html#numpy.unravel_index